### PR TITLE
Migrate from Webpack to Vite

### LINKED ISSUE #116: Remove Vue CLI Plugin Electron Builder
This library was last updated on June 24, 2021. Per https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/1677 it does not support Webpack 5, precluding an upgrade to Vue CLI 5 (itself only slightly less of a dead end than Vue CLI 4), which in turn precludes an upgrade to ESLint 8. Per https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/1959 it also does not support Node.js 18 and Electron 23. Clearly this dependency is a liability.

Per the [Vue.js tooling guide](https://vuejs.org/guide/scaling-up/tooling.html):

> [Vue CLI](https://cli.vuejs.org/) is the official webpack-based toolchain for Vue. It is now in maintenance mode and we recommend starting new projects with [Vite](https://vitejs.dev/) unless you rely on specific webpack-only features.

[Electron⚡️Vite](https://electron-vite.github.io/) appears to be the recommended tool for building a Vue.js 3 Electron application in 2023.

### PR DESCRIPTION
**Pull request by basil**
Fixes #116. At the moment I am not aware of any problems on this branch. Tested by running the Linux AppImage production build and verifying that I could play my existing scores and create new scores.

### CODE REVIEW

**Comment by basil** [comment]
I guess with this PR we've lost Typescript static analysis? I tried to add it back with

```
diff --git a/package.json b/package.json
index 61fc7e2..b8a42e9 100644
--- a/package.json
+++ b/package.json
@@ -16,8 +16,8 @@
   },
   "scripts": {
     "dev": "vite",
-    "build": "vite build && electron-builder",
-    "release": "vite build && electron-builder",
+    "build": "vue-tsc --noEmit && vite build && electron-builder",
+    "release": "vue-tsc --noEmit && vite build && electron-builder",
     "lint": "eslint --ext .js,.ts,.vue --ignore-path .gitignore src",
     "docs:dev": "vitepress dev docs",
     "docs:build": "vitepress build docs",
@@ -71,7 +71,8 @@
     "vite-plugin-electron-renderer": "^0.14.5",
     "vite-plugin-eslint": "^1.8.1",
     "vitepress": "^1.0.0-beta.5",
-    "vitest": "^0.33.0"
+    "vitest": "^0.33.0",
+    "vue-tsc": "^1.8.4"
   },
   "license": "GPL-3.0",
   "packageManager": "npm@9.5.1"
```

but there were hundreds of Typescript errors. I guess the newer build toolchain is more strict?

**Comment by danielgarthur** [comment]
Vue 3 now checks the templates. I figured there could be a separate PR to fix the errors. These are things like `:style` bindings should now take a `StyleValue` object instead of a `CSSStyleDeclaration`. And the editor now needs a bunch of typecasting in the templates, which I don't even think was possible in Vue 2.

**Comment by basil** [comment]
OK, I will leave this PR as-is then and file follow-up issues to cover `vue-tsc` and Vite PWA.

**Comment by basil** [comment]
Another thing I have just noticed is the print feature appears to be broken on this branch.

**Comment by basil** [comment]
I tracked down the printing problem to https://github.com/electron/electron/issues/39025. Downgraded Electron to 24.x and printing works again.

**Comment by basil** [comment]
I spent a few hours in this build today composing Axion Estins and did not come across any new problems.

**Review by danielgarthur — APPROVED** [review]

**Pull request merged**
